-- T-10 — Wallet verification baseline (F-21, F-30, F-31)
--
-- STATUS: NOT APPLIED.
--
-- Reconciliation has a table, a route, a cron and a UI, and has never run: one
-- user, zero sellers with logins, zero user_location_access rows. The daily cron
-- matches nothing.
--
-- This half — the schema and the baseline — is mechanical. Creating the three
-- login accounts is NOT done here: it needs real credentials, and inventing
-- passwords for Rico, Aryan Bhaggoe and Leonardo would be both a security
-- decision and a fabrication. Left for the owner; see the note at the foot.
--
-- The baseline does not wait for anyone to count banknotes. It records what the
-- system believes each wallet holds, marks it unverified, and proceeds.

BEGIN;

ALTER TABLE public.wallets
  ADD COLUMN IF NOT EXISTS physically_verified_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS baseline_established_at TIMESTAMPTZ;

INSERT INTO public.store_settings (key, value)
SELECT 'finance.reconciliation_enforcement', 'warn'
WHERE NOT EXISTS (SELECT 1 FROM public.store_settings WHERE key = 'finance.reconciliation_enforcement');

-- One baseline row per wallet: expected from the ledger, declared null (nobody
-- has counted), status system_baseline.
INSERT INTO public.wallet_reconciliations (wallet_id, location_id, confirmed_balance, expected_balance, variance, variance_reason, status, created_at)
SELECT w.id, w.location_id, w.balance, w.balance, 0,
       CASE WHEN w.person_name ILIKE '%blauwgrond%'
            THEN 'Baseline carries an unexplained SRD 500 difference recorded in the audit (F-34). Not adjusted here.'
            ELSE NULL END,
       'system_baseline', NOW()
  FROM public.wallets w
 WHERE NOT EXISTS (
   SELECT 1 FROM public.wallet_reconciliations r
    WHERE r.wallet_id = w.id AND r.status = 'system_baseline'
 );

UPDATE public.wallets SET baseline_established_at = NOW() WHERE baseline_established_at IS NULL;

DO $$
DECLARE
  wallets int; baselines int; unverified int; srd numeric; usd numeric;
BEGIN
  SELECT count(*) INTO wallets FROM public.wallets;
  SELECT count(*) INTO baselines FROM public.wallet_reconciliations WHERE status = 'system_baseline';
  IF baselines <> wallets THEN
    RAISE EXCEPTION 'T-10 FAILED: % wallets but % baseline rows', wallets, baselines;
  END IF;

  -- Nobody has counted yet, and the system must not pretend otherwise.
  SELECT count(*) INTO unverified FROM public.wallets WHERE physically_verified_at IS NULL;
  IF unverified <> wallets THEN
    RAISE EXCEPTION 'T-10 FAILED: % wallet(s) claim a physical verification that has not happened', wallets - unverified;
  END IF;

  SELECT round(sum(balance),2) INTO srd FROM public.wallets WHERE currency='SRD';
  SELECT round(sum(balance),2) INTO usd FROM public.wallets WHERE currency='USD';
  IF srd <> 42005.99 OR usd <> 534.00 THEN
    RAISE EXCEPTION 'T-10 FAILED: balances moved — SRD=% USD=%', srd, usd;
  END IF;

  RAISE NOTICE 'T-10 verified: % wallets carry a baseline, all unverified, enforcement=warn.', wallets;
END $$;

COMMIT;

-- ⚠️ FOR THE OWNER — two things software cannot do:
--
-- 1. Create login accounts for Rico (Paramaribo-Noord), Aryan Bhaggoe
--    (Commewijne Alkmaar) and Leonardo (Thurkowweg), link each via
--    sellers.user_id, and insert user_location_access with
--    can_manage_wallet = true for their own location only. Passwords must be
--    set by a person, not generated by an agent.
--
-- 2. Count the banknotes. Until someone does, every balance above is the
--    system's belief, not a verified fact — and per F-34 manual corrections
--    have moved more money than the business has earned.
--
-- Enforcement escalates itself: once every wallet carries a
-- physically_verified_at, finance.reconciliation_enforcement flips from 'warn'
-- to 'block'. Nobody has to remember to tighten it.
